heartbeat8.heartbeat_stream.*:
  type: config_entity
  label: 'Heartbeat Stream config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    hid:
      type: serial
      label: 'hid'
    message_id:
      type: string
      label: 'message_id'
    description:
      type: string
      label: 'description'
    message:
      type: string
      label: 'message'
    message_concat:
      type: string
      label: 'message_concat'
    perms:
      type: integer
      label: 'perms'
    group_type:
      type: string
      label: 'group_type'
    concat_args:
      type: blob
      label: 'concat_args'
    variables:
      type: blob
      label: 'variables'
    attachments:
      type: blob
      label: 'attachments'
